Repository tinkerbell/actions, pull requests merged in 2021-03, with the labels that each got.

#19 This adds Syslinux installation support as an action
  actions/syslinux/v1/Dockerfile
  actions/syslinux/v1/Makefile
  actions/syslinux/v1/README.md
  actions/syslinux/v1/go.mod
  actions/syslinux/v1/go.sum
  actions/syslinux/v1/main.go
Labels: ready-to-merge

#23 Fixes formatting issue
  actions/image2disk/v1/main.go
Labels: ready-to-merge

#31 Remove prettier because I don't understand it
  hack/ci-check.sh
  shell.nix
Labels: ready-to-merge

#33 Aligns readme to environment vars
  actions/archive2disk/v1/main.go
Labels: bug

#32 Slurp action
  actions/slurp/v1/.gitignore
  actions/slurp/v1/Dockerfile
  actions/slurp/v1/Makefile
  actions/slurp/v1/README.md
  actions/slurp/v1/go.mod
  actions/slurp/v1/go.sum
  actions/slurp/v1/main.go
  actions/slurp/v1/pkg/image/image.go
  actions/slurp/v1/server/main.go
Labels: enhancement
